### ISSUE TITLE
Use Spring Testcontainers Support

### ISSUE THREAD

**Issue by rwinch** [jimmyjames/fga-spring-examples#2]
It might be nice if the samples [leveraged Testcontainers support](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.testcontainers.at-development-time) to start up the openfga Docker container instead of requiring it to [manually be started](https://github.com/jimmyjames/fga-spring-examples/tree/1ee9a6d87de3d51bec435ffbdd5350d4be6ebed0/simple-no-auth#run-openfga).

If this sounds good, I can send a PR for this.

**Comment by jimmyjames** [comment]
@rwinch that would be a great improvement! Happy to accept a PR 👍

**Comment by Crain-32** [comment]
@rwinch Do you think it might be better to use the Spring Docker Compose Approach I've setup in my [baseline](https://github.com/Crain-32/spring-openfga-playground/blob/main/compose.yaml)? I've commented it in the [original issue](https://github.com/spring-projects/spring-security/issues/14121), but I'm interested in that approach just to see if we want to investigate a Docker Compose integration closer to the [Service Connections](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.docker-compose.service-connections) we have with built-in autoconfiguration as I've found those to be amazing for local development.

**Comment by rwinch** [comment]
> Do you think it might be better to use the Spring Docker Compose Approach

@Crain-32 Thanks for the idea! Docker Compose is another approach that works nicely. The advantage to using Testcontainers is that you can map the port of the docker image to a dynamic port (random available port) and update the Spring Environment to use the dynamic port. This ensures that the application will startup without any port collisions if the host machine is already using port 4000 for example. 

@jimmyjames I've submitted a PR https://github.com/jimmyjames/fga-spring-examples/pull/4 Apologies for lumping more than one commit in a single PR, but this ensures that you don't have to merge a bunch of PRs in a specific order.
