### ISSUE TITLE
Consider Single Sample Application

### ISSUE THREAD

**Issue by rwinch** [jimmyjames/fga-spring-examples#6]
I'd like us to consider switching to using a single sample application that performs basic authentication using in memory authentication with two different users.

I think that this will provide some advantages:

- It provides the simplest example of how the authorization behaves with an authenticated user
- It reduces the places that we will need to make changes as we sort through how things will work

Things to consider:

- The client sample could be placed in the tests rather than as a separate application. This ensures that things continue to work.
- Are there other types of authentication that will behave differently than HTTP Basic? If so, we may want to add these eventually.

**Comment by rwinch** [comment]
@jimmyjames I'm happy to submit a PR if you agree with this

**Comment by Crain-32** [comment]
I'd be fine adding in some In-Memory Basic auth when I make a PR to merge my baseline with this project. Meant to get to that last night, but got held up with other things.

**Comment by rwinch** [comment]
Thanks @Crain-32! Are you ok with a single sample or do you think there is value in doing more than one type of authN right now?

I'm curious if @jimmyjames's thoughts as well.

**Comment by Crain-32** [comment]
@rwinch I think a single sample works for now. We can increase the amount size once we get a better grasp.

The nice thing is because Spring Security is based around the `Authentication` Object, as long as we have a good handle on mapping from that, I'm very confident in our ability to handle other types of authentication.
